In [1]:
#Data preprocessing:Hanlding NA values
#Linear regression multiple variables

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df=pd.read_csv("houseprice.csv")
df

area   price  bedroom  age
0  2600  550000      3.0   20
1  3000  565000      4.0   15
2  3200  610000      NaN   18
3  3600  680000      3.0   30
4  4000  725000      5.0    8

In [4]:
#To fill NA value,u take the median

In [7]:
import math
median_bedroom=math.floor(df.bedroom.median())
median_bedroom

3

In [14]:
df.bedroom=df.bedroom.fillna(median_bedroom)
df

area   price  bedroom  age
0  2600  550000      3.0   20
1  3000  565000      4.0   15
2  3200  610000      3.0   18
3  3600  680000      3.0   30
4  4000  725000      5.0    8

In [16]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedroom','age']],df.price)

LinearRegression()

In [17]:
reg.coef_

array([  143.625, -6762.5  ,   337.5  ])

In [18]:
reg.intercept_

173112.5

In [19]:
reg.predict([[3000,3,40]])

array([597200.])

In [21]:
reg.predict([[2500,4,5]])

array([506812.5])